### PR TITLE
Render a fallback widget with debug info when rendering some message content fails

### PR DESCRIPTION
**Pull request by jhass**
Prevents crashes for cases like #37

### CODE REVIEW

**Comment by tclaus** [comment]
How to produce a error case, to see changes here?

**Comment by jhass** [comment]
Make a new post with
```
<http://example.org

http://example.com>
```

Note that I didn't spend much time to make this pretty here. It's something that should never happen and is just a fallback to prevent crashing the app and give us just enough info to debug the issue.

**Comment by tclaus** [comment]
> Make a new post with
> 
> ```
> <http://example.org
> 
> http://example.com>
> ```

Is the line break the important part? 
If I create a post like this - it look on webUI the same as in the App. WYSIWYG: 
The first one is build with well formatted markdown, the second was build like in your text.  If this is w
IMG_6A0310E36BB7-1

With this PR I see no difference in the App.

**Comment by jhass** [comment]
Yes, all the line breaks are important, remove any and it doesn't crash anymore.

**Review by tclaus — APPROVED** [review]
With this fix a error message is rendered. 
As a user I'd prefer not to see a shiny red text, but something which expresses less danger.. 
Maybe in this case a less saturated 'red' tone?

IMG_07B3250D0909-1

**Comment by jhass** [comment]
Ah well, I'd love to stick to color scheme and not add random colors here and there. Remember this is another "should never happen and if it happens it's a real bug" case.

**Pull request merged**
