### PR TITLE
Recent sessions on sign in page

### LINKED ISSUE #19: Bug/Usability: when opening ‚switch User‘ User is logged out immediately
When someone is just curious what "switch user" means.. 
image

There is no way to go back. "Cancel"

But you can just swipe right to go back to the main Ui. 
But then the current user is logged out. 
image

Bettler: when opening "switch user" (the login screen) from a logged in instance. Don't clear logged-in status. Until new credentials are entered. 
Provide a cancel option.

### PR DESCRIPTION
**Pull request by jhass**
closes #19

screenshot_phone_2020-11-03-19-53-54

### CODE REVIEW

**Review by tclaus — CHANGES_REQUESTED** [review]
(Was sure I submittet a review recently - it's gone) 
Functions are looking good, some minor issues: 
Bildschirmfoto 2020-11-04 um 08 35 54
The confirmation button looks a bit detailed - "Confirm deletion" - its already a confirmation dialog, so just "Delete" ("Löschen") would be enough to remove the session. 

Also a subline-text would be nice. The account is not deleted or removed from diaspora at all, but just the session inside the app. Maybe: 
"This will not remove your account from diaspora*" - as a extra textile? 

When someone has the glorious idea to add masses of accounts - at some point they slide out of visible screen. 
There sold be a scrollable widget or the maximum count of account should be limited. 
Bildschirmfoto 2020-11-04 um 08 44 42

**Comment by jhass** [comment]
It's not sliding out of the screen but already limited to five accounts :) 

Maybe instead of clarifying through a subline, we can find an even clearer wording for the title?

**Comment by tclaus** [comment]
When accounts are limited, there is no hint for this. 
A nice headline could be: "Remove session from insporation*?"

**Comment by jhass** [comment]
Well, we add a hint then next up is "How can I view all of them?" and we're bloating up the feature :)

**Comment by tclaus** [comment]
> Well, we add a hint then next up is "How can I view all of them?" and we're bloating up the feature :)

You absolute right. 
We can let it now, as it is. (Whats about simply disabling the login, if max number is reached?) 
But this is also UI-sugar and very rare used.

**Review by tclaus — APPROVED** [review]
👍🏻

**Pull request merged**
